name: Main

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #PACKAGES_USERNAME: ${{ github.actor }}
      #REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        run:
          ./pipe_build_up_test.sh

#jobs:
#  build-publish:
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_PASS: ${{ secrets.DOCKER_FOUNDATION_PASS }}
#      DOCKER_USER: ${{ secrets.DOCKER_FOUNDATION_USER }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Build and publish image
#        run:
#          ./pipe_build_up_test.sh

# jobs:
#   pre-build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#   build-publish:
#     needs: [pre-build]
#     permissions:
#       id-token: write
#       contents: write
#     uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_build_test_push_dockerhub.yml@main
#     secrets:
#       DOCKER_PASS: ${{ secrets.DOCKER_FOUNDATION_PASS }}
#       DOCKER_USER: ${{ secrets.DOCKER_FOUNDATION_USER }}
#       KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
#     with:
#       BUILD_COMMAND: pipe_build_up_test.sh
#       KOSLI_FLOW: image_dockerfile_augmenter